-- Alter foreign key columns from INTEGER to TEXT
-- This resolves 'invalid input syntax for type integer' when inserting UUIDs

DO $$
BEGIN
  -- Borrowers
  BEGIN ALTER TABLE borrowers ALTER COLUMN created_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- KYC Documents
  BEGIN ALTER TABLE kyc_documents ALTER COLUMN borrower_id TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
  BEGIN ALTER TABLE kyc_documents ALTER COLUMN uploaded_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
  BEGIN ALTER TABLE kyc_documents ALTER COLUMN verified_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Facilities
  BEGIN ALTER TABLE facilities ALTER COLUMN borrower_id TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Proposals
  BEGIN ALTER TABLE proposals ALTER COLUMN borrower_id TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
  BEGIN ALTER TABLE proposals ALTER COLUMN created_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Proposal Versions
  BEGIN ALTER TABLE proposal_versions ALTER COLUMN created_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Risk Scores
  BEGIN ALTER TABLE risk_scores ALTER COLUMN scored_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Risk Overrides
  BEGIN ALTER TABLE risk_overrides ALTER COLUMN approved_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Workflow
  BEGIN ALTER TABLE workflow_instances ALTER COLUMN assigned_to TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
  BEGIN ALTER TABLE workflow_actions ALTER COLUMN actor_id TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Audit Logs
  BEGIN ALTER TABLE audit_logs ALTER COLUMN actor_id TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Settings
  BEGIN ALTER TABLE settings ALTER COLUMN updated_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- User Roles
  BEGIN ALTER TABLE user_roles ALTER COLUMN user_id TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
  BEGIN ALTER TABLE user_roles ALTER COLUMN assigned_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Appraisal Cases
  BEGIN ALTER TABLE appraisal_cases ALTER COLUMN borrower_id TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
  BEGIN ALTER TABLE appraisal_cases ALTER COLUMN created_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;

  -- Credit Memos
  BEGIN ALTER TABLE credit_memos ALTER COLUMN reviewed_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
  BEGIN ALTER TABLE credit_memos ALTER COLUMN created_by TYPE TEXT; EXCEPTION WHEN OTHERS THEN END;
END $$;
